#!/usr/bin/env php
<?php

if(!isset($argv) || php_sapi_name() != 'cli')
    exit("Executavel apenas por linha de comando!\n");

require_once './console/TerminalListener.php';
require_once './console/Help.php';
require_once './console/InitPlugin.php';

if(!isset($argv[1]))
    $argv[1] = "no_argv";

do{

    switch($argv[1]){

        case 'init' :
            (new \MocaBonita\console\InitPlugin())->run($argv);
        break;

        default :
            (new \MocaBonita\console\Help())->run($argv);
        break;
    }

} while($argv[1] != 'exit');

exit();